# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('programme', models.CharField(max_length=10)),
                ('allowed_entries', models.IntegerField()),
                ('remaining_entries', models.IntegerField()),
            ],
        ),
    ]
